### ISSUE TITLE
cannot find app using Client App ID

### ISSUE THREAD

**Issue by progrish** [LuceCarter/HouseMovingAssistant#2]
When register or login in android, error thrown cannot find app using Client App ID.

**Comment by LuceCarter** [comment]
Are you able to share your config please where it stores the client app id?
I was demoing it on Android so wondering if it is a config issue

**Comment by progrish** [comment]
public static class AppConfig
	{
        public const string RealmAppId = "test";
    }

I think I set RealmAppId wrong. The same error  I  got in windows deploying.

**Comment by LuceCarter** [comment]
Yes you need to replace the value with your Realm client ID.
You can find it in Atlas, under App Services and clicking into your Realm app you created and it will be near the top :)
